opam-version: "2.0"
name: "diktor"
version: "dev"
synopsis: "Diktor is a bootstrap interpreter of the Keleut programming language, written in OCaml."
maintainer: "tomoaki3478@balux.org"
authors: ["Takezoe,Tomoaki"]
license: "Apache-2.0 WITH LLVM-exception"
build: [
  ["dune" "build" "-p" name "-j" jobs]
  ["dune" "runtest" "-p" name] {with-test}
]
depends: [
  "ocaml" {>= "5.2"}
  "dune" {>= "3.0"}
  "menhir"
  "sedlex"
]
