(library
 (public_name diktor)
 (libraries sedlex menhirLib)
 (modules lexer parser elab syntax aux env location)
 (preprocess
  (pps sedlex.ppx)))

(menhir
 (flags --explain)
 (modules parser))

(env
 (dev
  (flags
   ; Warning 8(非網羅 match)は noimpl の取りこぼし検出のため必ず残す
   (:standard -w +a-4-9-40-41-42-44-45-70)
   (:standard -warn-error -a+31))))
